# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"


gem "minitest", "~>5.6", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "rake-compiler", "~>0.7", :group => [:development, :test]
gem "hoe-bundler", ">=1.1", :group => [:development, :test]
gem "hoe-gemspec", ">=1.0", :group => [:development, :test]
gem "hoe-git", ">=1.4", :group => [:development, :test]
gem "minitest-focus", ">=0", :group => [:development, :test]
gem "rake", ">=0.9", :group => [:development, :test]
gem "gnuplot", ">=0", :group => [:development, :test]
gem "rubystats", ">=0", :group => [:development, :test]
gem "hoe", "~>3.13", :group => [:development, :test]

# vim: syntax=ruby
